apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deployment
  namespace: ns-B
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-app
          image: <Docker_Repo>/go-app:latest
          ports:
            - containerPort: 8080
